Presentation/AuthOperationsApp.WEB/Controllers/RoleController.cs
using AuthOperationsApp.Application.DTOs.Role;
using AuthOperationsApp.Application.Features.Commands.Role.UpdateRole;
using AuthOperationsApp.Application.Features.Queries.Role.GetAllRole;
using AuthOperationsApp.Infrastructure.Base;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AuthOperationsApp.WEB.Controllers
{
    [Authorize]
    public class RoleController : BaseController
    {
        public RoleController(IMediator mediator) : base(mediator)
        {
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> AllRoles()
        {
            GetAllRoleQueryRequest request = new GetAllRoleQueryRequest();

            GetAllRoleQueryResponse response = await Mediator.Send(request);

            if (!response.RoleListInfoDtos.Success)
            {
                return View(new { error = response.RoleListInfoDtos.Message });
            }
            return View(response.RoleListInfoDtos.RoleListDto);
            
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<JsonResult> GetAllRoles()
        {
            GetAllRoleQueryRequest request= new GetAllRoleQueryRequest();
            
            GetAllRoleQueryResponse response = await Mediator.Send(request);

            if (!response.RoleListInfoDtos.Success)
            {
                return Json(new { error = response.RoleListInfoDtos.Message });
            }
            return Json(response.RoleListInfoDtos.RoleListDto);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<JsonResult> UpdateRole([FromBody] UpdateRoleRequestDto roleRequestDto )
        {
            UpdateRoleCommandRequest request = new UpdateRoleCommandRequest();
            request.Id = Guid.Parse(roleRequestDto.Id);
            request.Name = roleRequestDto.Name;

            UpdateRoleCommandResponse response = await Mediator.Send(request);
            if (!response.UpdateRoleInfoDto.Success)
            {
                return Json(response.UpdateRoleInfoDto.Message);
            }
            return Json(response);
        }

        [HttpGet]
        [AllowAnonymous]
        public async  Task<ActionResult> GetList()
        {
            
            GetAllRoleQueryRequest request = new GetAllRoleQueryRequest();

            GetAllRoleQueryResponse response = await Mediator.Send(request);

            var data = response.RoleListInfoDtos.RoleListDto;
        
            return PartialView("GetList", data);
        }

    }
}

Presentation/AuthOperationsApp.WEB/Controllers/RoleGroupController.cs
using AuthOperationsApp.Application.DTOs.RoleGroup;
using AuthOperationsApp.Application.Features.Commands.RoleGroup.AssignGroupToRole;
using AuthOperationsApp.Application.Features.Commands.RoleGroup.AssignRoleToGroup;
using AuthOperationsApp.Application.Features.Commands.RoleGroup.UnassignGroupToRole;
using AuthOperationsApp.Application.Features.Commands.RoleGroup.UnassignRoleToGroup;
using AuthOperationsApp.Application.Features.Queries.Role.GetAllRoleByGroup;
using AuthOperationsApp.Application.Features.Queries.Role.GetAllRoleNoGroup;
using AuthOperationsApp.Application.Features.Queries.Role.GetRoleById;
using AuthOperationsApp.Application.Features.Queries.RoleGroup.GetAllGroupByRole;
using AuthOperationsApp.Application.Features.Queries.RoleGroup.GetAllGroupNoRole;
using AuthOperationsApp.Infrastructure.Base;
using MediatR;
using Microsoft.AspNetCore.Mvc;


namespace AuthOperationsApp.WEB.Controllers
{
    public class RoleGroupController : BaseController
    {
        public RoleGroupController(IMediator mediator) : base(mediator)
        {
        }

        //Yetkinin bağlı olduğu Gruplar kutucuğu - Yetkisiz Gruplar Kutucuğu Ekranı
        [HttpGet]
        public async Task<IActionResult> AllGroupsByRole(Guid id)
        {
            ViewBag.RoleId = id;
            return View();
        }

        //AllGroupsByRole sayfasına Roleismini getirir
        [HttpPost]
        public async Task<JsonResult> GetRoleName([FromBody] string RoleId)
        {
            GetRoleByIdQueryRequest request = new GetRoleByIdQueryRequest();
            request.Id = Guid.Parse(RoleId);
            GetRoleByIdQueryResponse response = await Mediator.Send(request);       

            if (response.RoleByIdInfoDto.Success)
            {
                return Json(new { RoleName = response.RoleByIdInfoDto.RoleByIdDto.Name });
            }
            return Json(new { error = response.RoleByIdInfoDto.Message });

        }

        //Yetkinin bağlı olduğu Gruplar
        [HttpPost]
        public async Task<JsonResult> GroupsByRole([FromBody] string RoleId)
        {

            GetAllGroupByRoleQueryRequest request = new GetAllGroupByRoleQueryRequest();
            request.RoleId = Guid.Parse(RoleId);
            GetAllGroupByUserQueryResponse response = await Mediator.Send(request);

            if (response.GroupByRoleInfoDto.Success)
                return Json(response.GroupByRoleInfoDto.GroupByRoleDto);
            else
                return Json(new { error = response.GroupByRoleInfoDto.Message });
        }

        //Yetkisi olmayan Gruplar kutucuğu   
        [HttpPost]
        public async Task<JsonResult> GroupsNoRole([FromBody] string RoleId)
        {
            GetAllGroupNoRoleQueryRequest request = new GetAllGroupNoRoleQueryRequest();
            request.RoleId = Guid.Parse(RoleId);

            GetAllGroupNoRoleQueryResponse response = await Mediator.Send(request);

            if (!response.AllGroupNoRoleInfoDto.Success)
            {
                Json(new { error = response.AllGroupNoRoleInfoDto.Message });
            }

            return Json(response.AllGroupNoRoleInfoDto.AllGroupNoRoleDto);
        }

        //Role Grup atama 
        [HttpPost]
        public async Task<JsonResult> AssignGroupToRole([FromBody] AssignGroupRequestDto requestDto)
        {
            if (ModelState.IsValid)
            {
                AssignGroupToRoleCommandRequest request = new AssignGroupToRoleCommandRequest();
                request.GroupId = Guid.Parse(requestDto.GroupId);
                request.RoleId = Guid.Parse(requestDto.RoleId);

                AssignGroupToRoleCommandResponse response = await Mediator.Send(request);

                if (response.AssignGroupToRoleInfoDto.Success)
                    return Json(response.AssignGroupToRoleInfoDto.Message);
                else
                    return Json(new { error = response.AssignGroupToRoleInfoDto.Message });
            }

            return Json(new { error = "Invalid model state" });
        }

        //Roleden Grup atamasını kaldırma
        [HttpPost]
        public async Task<JsonResult> UnassignGroupToRole([FromBody] UnassignGroupRequestDto requestDto)
        {
            if (ModelState.IsValid)
            {
                UnassignGroupToRoleCommandRequest request = new UnassignGroupToRoleCommandRequest();
                request.GroupId = Guid.Parse(requestDto.GroupId);
                request.RoleId = Guid.Parse(requestDto.RoleId);

                UnassignGroupToRoleCommandResponse response = await Mediator.Send(request);

                if (response.UnassignGroupToRoleInfoDto.Success)
                    return Json(response.UnassignGroupToRoleInfoDto.Message);
                else
                    return Json(new { error = response.UnassignGroupToRoleInfoDto.Message });
            }
            return Json(new { error = "Invalid model state" });
        }

        //Grubun sahip oldupu Yetkiler kutucuğu - Grubun sahip olmadığı Yetkiler Kutucuğu Ekranı
        [HttpGet]
        public async Task<IActionResult> AllRolesByGroup(Guid id)
        {
            ViewBag.GroupId = id;
            ViewBag.GroupName = "";
            return View();
        }

        //Grubun sahip olduğu Yetkiler kutucuğu
        [HttpPost]
        public async Task<JsonResult> RolesByGroup([FromBody] string GroupId)
        {
            GetAllRoleByGroupQueryRequest request = new GetAllRoleByGroupQueryRequest();
            request.GroupId = Guid.Parse(GroupId);
            GetAllRoleByGroupQueryResponse response = await Mediator.Send(request);

            if (response.RoleByGroupInfoDto.Success)
                return Json(response.RoleByGroupInfoDto.RoleByGroupDto);
            else
                return Json(new { error = response.RoleByGroupInfoDto.Message });
        }

        // Grubun sahip olmadığı Yetkiler kutucuğu
        [HttpPost]
        public async Task<JsonResult> RolesNoGroup([FromBody] string GroupId)
        {
            GetAllRoleNoGroupQueryRequest request = new GetAllRoleNoGroupQueryRequest();
            request.GroupId = Guid.Parse(GroupId);

            GetAllRoleNoGroupQueryResponse response = await Mediator.Send(request);

            if (!response.AllRoleNoGroupInfoDto.Success)
            {
                Json(new { error = response.AllRoleNoGroupInfoDto.Message });
            }

            return Json(response.AllRoleNoGroupInfoDto.AllRoleNoGroupDto);
        }

        //Gruba Role atama 
        [HttpPost]
        public async Task<JsonResult> AssignRoleToGroup([FromBody] AssignRoleRequestDto requestDto)
        {
            if (ModelState.IsValid)
            {
                AssignRoleToGroupCommandRequest request = new AssignRoleToGroupCommandRequest();
                request.GroupId = Guid.Parse(requestDto.GroupId);
                request.RoleId = Guid.Parse(requestDto.RoleId);

                AssignRoleToGroupCommandResponse response = await Mediator.Send(request);

                if (response.AssignRoleToGroupInfoDto.Success)
                    return Json(response.AssignRoleToGroupInfoDto.Message);
                else
                    return Json(new { error = response.AssignRoleToGroupInfoDto.Message });
            }
            return Json(new { error = "Invalid model state" });
        }

        //Gruptan Role atamasını kaldırma
        [HttpPost]
        public async Task<JsonResult> UnassignRoleToGroup([FromBody] UnassignRoleRequestDto requestDto)
        {
            if (ModelState.IsValid)
            {
                UnassignRoleToGroupCommandRequest request = new UnassignRoleToGroupCommandRequest();
                request.GroupId = Guid.Parse(requestDto.GroupId);
                request.RoleId = Guid.Parse(requestDto.RoleId);

                UnassignRoleToGroupCommandResponse response = await Mediator.Send(request);

                if (response.UnassignRoleToGroupInfoDto.Success)
                    return Json(response.UnassignRoleToGroupInfoDto.Message);
                else
                    return Json(new { error = response.UnassignRoleToGroupInfoDto.Message });
            }
            return Json(new { error = "Invalid model state" });
        }
    }
}

Presentation/AuthOperationsApp.WEB/Views/Role/AllRoles.cshtml
@using AuthOperationsApp.Application.DTOs.Role
@model List<RoleListDto>
@{
    ViewData["Title"] = "Yetkiler";
}

<div class="row">
    <div class="col-4 offset-4">
        <h1 class="display4 border-bottom text-center pb-2">@ViewData["Title"]</h1>
    </div>
</div>


<div class="card">
    <div class="card-body">

        <div id="Tablelist" class="col-md-12">
         

        </div>

    </div>
</div>


<div class="modal fade" id="updateRoleModal" tabindex="-1" role="dialog" aria-labelledby="updateRoleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateRoleModalLabel">Yetki Güncelleme</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="text" id="txtRoleName" class="form-control" value="" />
                <input type="hidden" id="txtRoleId" value="" />
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                    <button id="btnRoleSave" type="submit" class="btn btn-dark">Kaydet</button>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {

    <script type="text/javascript">

        $(document).ready(function () {

            GetList();

            $(".btnEdit").on("click", function () {
                //Tıklanan düğmenin veri özelliklerinden rol adını ve id yi alırız
                var name = $(this).data("name");
                var id = $(this).data("id");

                //Modalın içini doldurur
                $("#txtRoleName").val(name);
                $("#txtRoleId").val(id);

                $("#updateRoleModal").modal("show");
            });

            $("#btnRoleSave").on("click", function () {

                var UpdateRoleRequestDto = {}
                UpdateRoleRequestDto.Id = $("#txtRoleId").val();
                UpdateRoleRequestDto.Name = $("#txtRoleName").val();

                $.ajax({
                    type: "POST",
                    url: "/Role/UpdateRole",
                    data: JSON.stringify(UpdateRoleRequestDto),
                    contentType: 'application/json; charset=utf-8',
                    success: function (result) {

                        console.log(result);
                        $("#updateRoleModal").modal("hide");
                        
                        location.reload();
                    },
                    error: function (ex) {
                        console.log(ex);
                        alert("An error occurred while processing the request.");
                    }
                });


            });
        });



        function GetList() {
            var table = $("#Tablelist");

            $.ajax({
                type: "GET",
                url: "/Role/GetList",
                dataType:"html",
                cache:false,
                success: function (result) {

                    console.log(result);
                    if (result != null) {
                        table.html(result);
                    }                    
                },
                error: function (ex) {
                    console.log(ex);
                    alert("An error occurred while processing the request.");
                }
            });
        }        

    </script>
} 

Presentation/AuthOperationsApp.WEB/Views/Role/GetList.cshtml
@using AuthOperationsApp.Application.DTOs.Role
@model List<RoleListDto>

<table class="table table-bordered table-striped mt-4 table-responsive">
    <tbody>
        @foreach (var group in Model)
        {
            <tr>
                <td>@group.Name</td>
                <td>
                    <a asp-action="AllRolesByGroupId" asp-controller="RoleGroup" asp-route-groupId="@group.Id" class="btn btn-secondary"><i class="fa-solid fa-cart-plus"></i> Yetkinin Bağlı Olduğu Grupları Göster</a>
                </td>

                <td>
                    <a data-name="@group.Name" data-id="@group.Id" class="btn btn-warning btnEdit"><i class="fa-solid fa-cart-plus"></i> Düzenle</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Presentation/AuthOperationsApp.WEB/Views/Role/UpdateRole.cshtml
@model UpdateRoleCommandResponse

@{
    ViewData["Title"] = "Yetki Güncelleme";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="modal fade" id="updateRoleModal" tabindex="-1" role="dialog" aria-labelledby="updateRoleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateRoleModalLabel">Yetki Güncelleme</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="updateRoleForm" data-val="true" method="post">

                    <div asp-validation-summary="ModelOnly" class="text-danger small"></div>

                    <label asp-for="UpdateRoleInfoDto.UpdateRoleDto.Name"></label>
                    <input asp-for="UpdateRoleInfoDto.UpdateRoleDto.Name" class="form-control" />
                    <span asp-validation-for="UpdateRoleInfoDto.UpdateRoleDto.Name" class="text-danger small"></span>
                    <br />

                    <button type="submit" class="btn btn-dark">Güncelle</button>

                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    
    <script>
        $(document).ready(function () {
            $("#updateRoleForm").submit(function (e) {
                e.preventDefault();

                $("#updateRoleModal").modal("hide");
            });
        });
    </script>
}